"""add table rejections for childs

Revision ID: 10dcc78c2502
Revises: c426b67013df
Create Date: 2024-05-18 11:02:18.617688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dcc78c2502'
down_revision: Union[str, None] = 'c426b67013df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childrenrejections',
    sa.Column('children_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['videocategory.id'], ),
    sa.ForeignKeyConstraint(['children_name'], ['childrens.name'], ),
    sa.PrimaryKeyConstraint('children_name', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('childrenrejections')
    # ### end Alembic commands ###
