"""add childs

Revision ID: 7bd8686482e0
Revises: daa839800311
Create Date: 2024-05-18 08:24:01.429267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd8686482e0'
down_revision: Union[str, None] = 'daa839800311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childrens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_childrens_id'), 'childrens', ['id'], unique=False)
    op.create_index(op.f('ix_childrens_name'), 'childrens', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_childrens_name'), table_name='childrens')
    op.drop_index(op.f('ix_childrens_id'), table_name='childrens')
    op.drop_table('childrens')
    # ### end Alembic commands ###
