"""add table rejections for childs

Revision ID: c426b67013df
Revises: d4f2e6067271
Create Date: 2024-05-18 11:02:03.367689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c426b67013df'
down_revision: Union[str, None] = 'd4f2e6067271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_childrens_name', table_name='childrens')
    op.create_index(op.f('ix_childrens_name'), 'childrens', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_childrens_name'), table_name='childrens')
    op.create_index('ix_childrens_name', 'childrens', ['name'], unique=False)
    # ### end Alembic commands ###
