"""uniq to tags

Revision ID: d4f2e6067271
Revises: 7bd8686482e0
Create Date: 2024-05-18 09:43:26.993698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f2e6067271'
down_revision: Union[str, None] = '7bd8686482e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videocategory', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videocategory', type_='unique')
    # ### end Alembic commands ###
