"""9

Revision ID: d5a324bd7a72
Revises: bad539dbf02e
Create Date: 2024-05-18 18:35:46.059174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a324bd7a72'
down_revision: Union[str, None] = 'bad539dbf02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historywatch', sa.Column('children_name', sa.String(), nullable=False))
    op.drop_constraint('historywatch_user_id_fkey', 'historywatch', type_='foreignkey')
    op.create_foreign_key(None, 'historywatch', 'childrens', ['children_name'], ['name'])
    op.drop_column('historywatch', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historywatch', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'historywatch', type_='foreignkey')
    op.create_foreign_key('historywatch_user_id_fkey', 'historywatch', 'users', ['user_id'], ['id'])
    op.drop_column('historywatch', 'children_name')
    # ### end Alembic commands ###
